### ISSUE TITLE
Latest PADD added line breaks on PiTFT 3.5" - some content beyond range of screen

### ISSUE THREAD

**Issue by sa-rat** [pi-hole/PADD#76] opened 2020-02-24 03:29 UTC
Updated Pi-hole and PADD this morning.

New PADD now has extra line breaks below each heading (FTL ===, NETWORK ===, DNS === etc.) causing the range of output to go beyond the screen resolution of the 3.5" PiTFT.
Logo, version and health information is no longer displayed as a result.

To Reproduce:
Update Pi-hole and PADD. Reboot.

Expected Behaviour:
PADD logo, version info and health status should be displayed at top of PiTFT 3.5"

Screenshot: 
![IMG_20200224_102133](https://user-images.githubusercontent.com/51199133/75127194-6e3f3f80-56f0-11ea-922c-60215d70bde0.jpg)

**Comment by Fede068** [comment] 2020-02-24 12:59
Have exact the same problem after the Update!

**Comment by dw808303** [comment] 2020-02-24 14:04
I’ve reproduced this on my installation as well.

**Comment by famesjranko** [comment] 2020-02-24 15:33
confirmed for me as well.  I found editing the script and removing an "=" from each of the lines before new added blank lines fixed the issue, but can't understand why.

**Comment by derekschinke** [comment] 2020-02-24 19:17
Exact same issue here, for every font size that I have tried.

**Comment by jpmck** [comment] 2020-02-24 19:21
Noticed the same thing when I checked on my PADD, which resides in the basement.

I'm working on a fix for this that should be deployed in the next couple of days.

**Comment by tgjohnst** [comment] 2020-02-24 19:49
Sorry for introducing a bug! Didn't happen when I tested the various sizes but it looks like this is happening when the screen size is exactly the length of the header lines. I'm thinking the additional escape character to clear to end of terminal may count as another drawn character and push the line over the limit so it wraps to a newline?

Was thinking as part of my previous PR about dynamically drawing the == signs to screen length rather than using fixed #s, but didn't get that far...

**Comment by chrisjeb** [comment] 2020-02-24 21:51
Hi,

Tnx for all your hard work but i seems to have same issue

**Comment by Kentsson** [comment] 2020-02-28 21:53
Same issue here

**Comment by ChappyEight** [comment] 2020-02-29 01:26
Seems to be relatively universal.  Same issue here after updating tonight.

**Comment by todrees1967** [comment] 2020-02-29 16:40
Same issue here as well.

**Comment by R3clu23** [comment] 2020-02-29 18:55
Same issue.
![20200229_132949](https://user-images.githubusercontent.com/23437687/75613392-1ee77d80-5afb-11ea-83c5-0ed529cb004f.jpg)

**Comment by sgu222e** [comment] 2020-02-29 23:22
Adding my name to the list of people affected.

**Comment by vekzla** [comment] 2020-03-01 03:38
Same here also reporting padd is out of date even though I have updated to latest.

**Comment by Kentsson** [comment] 2020-03-01 08:41
Try removing the piHoleversion file (not sure about the name since I can't check it out now)

On 1 March 2020 04:38:45 CET, vekzla <notifications@github.com> wrote:
>Same here also reporting padd is out of date even though I have updated
>to latest. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jpmck/PADD/issues/76#issuecomment-593048898

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by vekzla** [comment] 2020-03-01 09:45
> Try removing the piHoleversion file (not sure about the name since I can't check it out now)
> […](#)
> On 1 March 2020 04:38:45 CET, vekzla ***@***.***> wrote: Same here also reporting padd is out of date even though I have updated to latest. -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#76 (comment)](https://github.com/jpmck/PADD/issues/76#issuecomment-593048898)
> -- Sent from my Android device with K-9 Mail. Please excuse my brevity.

Thank you for your reply, I have removed the piholeVersion file (you got the name correct) and rebooted the raspi, still showing updates available. See pic below of my issues (screen stretched similar to others above and still showing updates are available) 

![image](https://user-images.githubusercontent.com/47047226/75623367-73732180-5bfd-11ea-967f-e03f271df6ec.png)

thank you for your assistance

**Comment by sgu222e** [comment] 2020-03-03 01:21
So, I found a hackish fix for this.
Remove 1 = from the CleanEcho command that displays the name of each section for the regular/slim display. It seems like the 80th character is causing a wrap to the next line to display blank.
lines changed:  636, 646, 653, 673, 704, 715, 722, 748 and 759

Hope that helps someone.

**Comment by vekzla** [comment] 2020-03-05 07:18
> So, I found a hackish fix for this.
> Remove 1 = from the CleanEcho command that displays the name of each section for the regular/slim display. It seems like the 80th character is causing a wrap to the next line to display blank.
> lines changed: 636, 646, 653, 673, 704, 715, 722, 748 and 759
> 
> Hope that helps someone.

Can Confirm this has worked on 7inch TFT touch screen, also fixed the update issue by following https://github.com/jpmck/PADD/issues/87

**Comment by krispayne** [comment] 2020-03-05 22:55
> So, I found a hackish fix for this.
> Remove 1 = from the CleanEcho command that displays the name of each section for the regular/slim display. It seems like the 80th character is causing a wrap to the next line to display blank.
> lines changed: 636, 646, 653, 673, 704, 715, 722, 748 and 759
> 
> Hope that helps someone.

This also resolved the issue on my 3.5" display

**Comment by Fede068** [comment] 2020-03-06 09:02
> So, I found a hackish fix for this.
> Remove 1 = from the CleanEcho command that displays the name of each section for the regular/slim display. It seems like the 80th character is causing a wrap to the next line to display blank.
> lines changed: 636, 646, 653, 673, 704, 715, 722, 748 and 759
> 
> Hope that helps someone.

This fix works perfect also for my display adafruit PiTFT+ 3.5". Thank you!

**Comment by ChappyEight** [comment] 2020-03-16 21:14
Apologies as I'm a bit of a RPi novice.  Aside from the hack posted above, has there been an official fix posted?

**Comment by accordxtc** [comment] 2020-03-18 00:11
I would like to know as well for a notice how we can go about doing the above hack. Thanks in advance

**Comment by VeryColdAir** [comment] 2020-03-25 22:14
> So, I found a hackish fix for this.
> Remove 1 = from the CleanEcho command that displays the name of each section for the regular/slim display. It seems like the 80th character is causing a wrap to the next line to display blank.
> lines changed: 636, 646, 653, 673, 704, 715, 722, 748 and 759
> Hope that helps someone.

I change those lines and then rebooted. I saw that the line that started with DNS still had an empty line below it.

I changed delete a "=" from line 649 and it fixed it.

**Comment by VeryColdAir** [comment] 2020-03-25 22:37
> I would like to know as well for a notice how we can go about doing the above hack. Thanks in advance


If you don't have ssh enabled on your raspberry pi, take a look at [the official documentation for how to enable it](https://www.raspberrypi.org/documentation/remote-access/ssh/). (Skip to step 3 on the list there.)  If you don't want to use ssh, then skip to the second method on the post.

If you have one of the latest versions of windows 10, you can run `ssh pi@<ip address>` to ssh into the pi, no third-party software like putty required anymore. (Might have to enable first party ssh tool, but for me it was there by default).


==========================

One of the easiest ways I know of, _that avoids the use of a terminal text-editor_, is to get the NppFTP addin for NotePad++. This assumes you had ssh set up.

Within the NppFTP window, you can set up a profile for the raspberry pi running pi hole. 

1. Use the IP address for the host name
2. Set the connection type to SFTP (port will default to 22, which is what it'll need to be unless you changed the port)
3. Enter the device's username and password (default u: pi p: raspberry)
4. Set the initial remote directory to: "/home/pi/".

When you first connect, it will show a hash key(?) and ask if you want to accept/trust it. Hit yes and then on the file explorer panel below the profile and connection buttons, you should see the subdirectories of the /home/pi/ directory as well as the files within /home/pi/, include padd.sh. Double click on padd.sh to open it. Once it's open, change the lines that @sgu222e mentioned, and you should be good to go.


==========================

If you'd rather edit using the terminal only, then either use ssh to access the pi's terminal or plug a keyboard & mouse in to do it directly. I believe if you're going to plug a keyboard and mouse in, you can press ctrl+c to stop padd and give you control of the terminal. (Not 100% sure that will work.)

When I did it, I was already in the /home/pi/ directory, but if you want to make sure you're there, you can run the command:
`cd /home/pi/`

To see everything in the directory, run the command:
`ls`

You should see padd.sh listed. To edit it, run the command:
`nano padd.sh`

You'll then be able to go though the file and make changes to it. For the commands at the bottom, press ctrl and the character show to activate the command. (^x means ctrl+x)

**Comment by astronyu** [comment] 2020-04-03 05:42
> 
> 
> So, I found a hackish fix for this.
> Remove 1 = from the CleanEcho command that displays the name of each section for the regular/slim display. It seems like the 80th character is causing a wrap to the next line to display blank.
> lines changed: 636, 646, 653, 673, 704, 715, 722, 748 and 759
> 
> Hope that helps someone.

Thanks for sharing. I have no idea how to use CleanEcho command so went into editor and change it manually. It works!

**Comment by dawnchorus** [comment] 2020-05-07 14:05
> So, I found a hackish fix for this.
> Remove 1 = from the CleanEcho command that displays the name of each section for the regular/slim display. It seems like the 80th character is causing a wrap to the next line to display blank.
> lines changed: 636, 646, 653, 673, 704, 715, 722, 748 and 759
> 
> Hope that helps someone.

Sorry, this must be fairly basic but how can I navigate to those exact lines? I can get through to the directory but there is no way I can see what number line I am looking at.

**Comment by astronyu** [comment] 2020-05-07 14:17
> 
> 
> > So, I found a hackish fix for this.
> > Remove 1 = from the CleanEcho command that displays the name of each section for the regular/slim display. It seems like the 80th character is causing a wrap to the next line to display blank.
> > lines changed: 636, 646, 653, 673, 704, 715, 722, 748 and 759
> > Hope that helps someone.
> 
> Sorry, this must be fairly basic but how can I navigate to those exact lines? I can get through to the directory but there is no way I can see what number line I am looking at.

If you're using vi editor, follow this guide: https://kb.iu.edu/d/afcx
For nano, ctrl+_ will ask you the line to go to.

**Comment by dawnchorus** [comment] 2020-05-07 14:27
> > > So, I found a hackish fix for this.
> > > Remove 1 = from the CleanEcho command that displays the name of each section for the regular/slim display. It seems like the 80th character is causing a wrap to the next line to display blank.
> > > lines changed: 636, 646, 653, 673, 704, 715, 722, 748 and 759
> > > Hope that helps someone.
> > 
> > 
> > Sorry, this must be fairly basic but how can I navigate to those exact lines? I can get through to the directory but there is no way I can see what number line I am looking at.
> 
> If you're using vi editor, follow this guide: https://kb.iu.edu/d/afcx
> For nano, ctrl+_ will ask you the line to go to.

Thanks! It's better now but still not working all the way. I was able to navigate to the lines to delete the extra "="s from lines 636, 646, 653, 673, 704, 715, 722, 748 and 759 as well as 649 pointed out by "VeryColdAir"

The first line "PI-HOLE=====..." now shows up, however the PADD logo and version #, system healthy, etc. info still is not showing. Any ideas?

<img width="966" alt="Screen Shot 2020-05-07 at 16 26 38" src="https://user-images.githubusercontent.com/64970097/81306277-926bb500-907f-11ea-8936-1d4b065e2232.png">

**Comment by astronyu** [comment] 2020-05-07 14:54
I've uploaded my padd.sh to pastebin **[here](https://pastebin.com/zZjHy45F)**

**Comment by dawnchorus** [comment] 2020-05-09 20:19
> I've uploaded my padd.sh to pastebin **[here](https://pastebin.com/zZjHy45F)**

thanks for this! Works perfectly now

**Comment by FlappingBerd** [comment] 2020-06-26 00:30
> > So, I found a hackish fix for this.
> > Remove 1 = from the CleanEcho command that displays the name of each section for the regular/slim display. It seems like the 80th character is causing a wrap to the next line to display blank.
> > lines changed: 636, 646, 653, 673, 704, 715, 722, 748 and 759
> > Hope that helps someone.
> 
> Can Confirm this has worked on 7inch TFT touch screen, also fixed the update issue by following #87

I cant seem to get my 7" screen to fill completely - only around 80% is used. Any idea on how I may be able to maximize the use? For reference I am running a the Raspberry Pi 7" touchscreen.

**Comment by derekschinke** [comment] 2020-07-03 19:06
Updated,  and still have the exact same issue.

**Comment by dschaper** [comment] 2020-07-12 17:27
Can I get some values from `tput lines` and `tput cols` to see what the display values are?

**Comment by sgu222e** [comment] 2020-07-15 02:38
> Can I get some values from `tput lines` and `tput cols` to see what the display values are?

3.5" 
pi@pihole:~ $ tput lines
24
pi@pihole:~ $ tput cols
80

**Comment by mycomachine** [comment] 2020-09-09 02:36
whats that lovely blue color

**Comment by yubiuser** [comment] 2022-08-20 17:25
Closing this issue because there was no activity >2 years and a lot of new released of `PADD` were made.

**Closed by yubiuser** 2022-08-20 17:25 UTC
Labels: Bug Report
