### ISSUE TITLE
Version check fails.

### ISSUE THREAD

**Issue by deepcore2** [pi-hole/PADD#97] opened 2020-04-20 21:21 UTC
My PADD says it's out of date, but I run 3.1 which is latest ASFAK. I looked at the version check in the code and that seems to be faulty. TYhe check is:

curl -sI https://github.com/jpmck/PADD/releases/latest | grep 'Location' | awk -F '/' '{print $NF}' | tr -d '\r\n[:alpha:]'

Which returns nothing. Location is not withj a captital L. C The following check returns 3.1:

curl -sI https://github.com/jpmck/PADD/releases/latest | grep 'location' | awk -F '/' '{print $NF}' | tr -d '\r\n[:alpha:]'

Please fix.

**Comment by sgu222e** [comment] 2020-04-22 23:51
Duplicate of #73

**Comment by downtime0** [comment] 2020-05-22 21:42
@deepcore2 thanks for case sensitivity fix. I fixed mine the same and later found someone suggest removing the "grep" and simplify the line.

<code>
padd_version_latest=$(curl -sI https://github.com/jpmck/PADD/releases/latest | awk -F '/' '/location/ {print $NF}' | tr -d '\r\n[:alpha:]')
</code>

**Comment by regnare** [comment] 2020-06-05 13:25
> @deepcore2 thanks for case sensitivity fix. I fixed mine the same and later found someone suggest removing the "grep" and simplify the line.
> 
> ` padd_version_latest=$(curl -sI https://github.com/jpmck/PADD/releases/latest | awk -F '/' '/location/ {print $NF}' | tr -d '\r\n[:alpha:]') `

You could also pass -i to grep to make it case insensitive.
```
# PADD version information...
padd_version_latest=$(curl -sI https://github.com/jpmck/PADD/releases/latest | grep -i 'Location' | awk -F '/' '{print $NF}' | tr -d '\r\n[:alpha:]')
```

**Closed** 2020-07-12 17:15 UTC
