### ISSUE TITLE
Number of === is to high in regular size

### ISSUE THREAD

**Issue by deepcore2** [pi-hole/PADD#96] opened 2020-04-20 21:17 UTC
When I run PADD on my PiTft screen it runs regular. But due to too many "=" characters I get a blank line after that, forcing the logo and version line off of the screen. I manually removed one "=" from the output and now it displays fine. Please fix.

**Comment by Morrolan** [comment] 2020-04-21 14:10
This appears to be a duplicate of #76 and #84.

**Comment by dschaper** [comment] 2020-07-12 17:29
See #76

**Closed by dschaper** 2020-07-12 17:29 UTC
Labels: Duplicate Issue
