### ISSUE TITLE
Illegal number: inf / Pi-Hole versions not showing

### ISSUE THREAD

**Issue by Yaff1e** [pi-hole/PADD#224] opened 2022-05-26 12:31 UTC
*Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!*

**Describe the bug**

v3.7.0 and 3.7.1 show the errors below when loading. If loading completes it then shows v in all the Pi-Hole versions.

PADD version file not found

./padd.sh: 882: [: Illegal number: inf
./padd.sh: 884: [: Illegal number: inf
./padd.sh: 882: [: Illegal number: inf
./padd.sh: 884: [: Illegal number: inf
./padd.sh: 882: [: Illegal number: inf
./padd.sh: 884: [: Illegal number: inf

**To Reproduce**

Load PADD

**Expected behavior**

PADD to load and show version numbers

**Screenshots**

![image](https://user-images.githubusercontent.com/11681244/170485896-4cc0fc56-937f-4bad-b79d-73f07304a957.png)

![image](https://user-images.githubusercontent.com/11681244/170487311-47076049-f284-4159-a729-be3a4c3d4276.png)

**Additional context**

I updated to v3.7.0 yesterday and 3.7.1 today on both of my Pi-Holes. One of them is fine but the other not. It shows the errors above when loading. It then sits on that screen for a long time and either doesn't go past it or if it does it shows v in all the Pi-Hole versions with the same errors at the bottom of the screen.

**Comment by yubiuser** [comment] 2022-05-26 12:34
What's the output of `pihole -v`

**Comment by Yaff1e** [comment] 2022-05-26 12:35
![image](https://user-images.githubusercontent.com/11681244/170488809-ccf59470-3fc2-4d77-9195-27f824cf4d1e.png)

**Comment by yubiuser** [comment] 2022-05-26 20:31
The version numbers are very likely a red hering. The issue is

https://github.com/pi-hole/PADD/blob/4c888a894bb4c7e2b4a4526c17c21b1b9b14d31e/padd.sh#L240

returning `inf` (infinity).

What is your output of `cat /sys/devices/system/cpu/kernel_max`

**Comment by Yaff1e** [comment] 2022-05-26 21:01
It returns 0

**Comment by yubiuser** [comment] 2022-05-26 22:08
@Yaff1e 

We discovered the bug. Please try if this version is fixing the issue for you:
https://github.com/pi-hole/PADD/blob/fix/core_count/padd.sh

**Comment by Yaff1e** [comment] 2022-05-26 22:42
Yes, that's fixed it thanks.

**Comment by Yaff1e** [comment] 2022-05-27 13:18
That returns 1

**Comment by yubiuser** [comment] 2022-07-30 20:19
Fixed with https://github.com/pi-hole/PADD/releases/tag/v3.8.0

**Closed by yubiuser** 2022-07-30 20:19 UTC
Labels: Fixed in next release
