### ISSUE TITLE
PADD reporting new version, despite already being the current version

### ISSUE THREAD

**Issue by cmdshft** [pi-hole/PADD#73] opened 2020-02-20 21:50 UTC
*Before submitting a bug report, are you using a test version of Pi-hole? If so, PADD doesn‘t support beta versions of Pi-hole!*

**Describe the bug**
PADD is reporting an update available, labeled v3.0.2 as red and says [!] Updates are available, despite 3.0.2 being the current (at the time of this report) version.

**To Reproduce**
Run PADD

**Expected behavior**
Obvious.

**Screenshots**
![IMG_5790](https://user-images.githubusercontent.com/8571823/74981904-14452e00-5401-11ea-9d7e-73b929410ac0.JPG)

**Comment by knightphoenix** [comment] 2020-02-21 01:25
This is most likely being caused by the version number not being updated on the last commit. This can be checked by trying to update. Does updating fix the issue?

**Comment by cmdshft** [comment] 2020-02-21 05:04
I have done that and it's not resolved.

**Comment by danozdotnet** [comment] 2020-02-28 07:20
#493      padd_version_latest=$(curl -sI https://github.com/jpmck/PADD/releases/latest | grep 'Location' | awk -F '/' '{print $NF}' | tr -d '\r\n[:alpha:]')

The grep is looking for 'Location' when infact it's now 'location', the case changed. Secondly, no need to run grep then awk, just do it in one:

curl -sI https://github.com/jpmck/PADD/releases/latest | awk -F '/' '/location/ {print $NF}' | tr -d '\r\n[:alpha:]'

**Comment by sionide0278** [comment] 2020-03-02 02:18
> 
> 
> #493 padd_version_latest=$(curl -sI https://github.com/jpmck/PADD/releases/latest | grep 'Location' | awk -F '/' '{print $NF}' | tr -d '\r\n[:alpha:]')
> 
> The grep is looking for 'Location' when infact it's now 'location', the case changed. Secondly, no need to run grep then awk, just do it in one:
> 
> curl -sI https://github.com/jpmck/PADD/releases/latest | awk -F '/' '/location/ {print $NF}' | tr -d '\r\n[:alpha:]'

Replicated on v3.1 and fixed by changing Location to location

**Closed** 2020-07-12 17:15 UTC
